// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.mattermost.plugin-message-disappear",
    "name": "Disappearing Messages",
    "description": "Brings Enterprise-grade hard-delete message retention to the Team edition: set a per-channel TTL and expired messages are purged from the database.",
    "homepage_url": "https://github.com/naicoi92/mattermost-plugin-message-disappear",
    "support_url": "https://github.com/naicoi92/mattermost-plugin-message-disappear/issues",
    "release_notes_url": "https://github.com/naicoi92/mattermost-plugin-message-disappear/releases",
    "version": "1.1.0",
    "min_server_version": "10.0.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "Disappearing Messages settings. See the README for the hard-delete (D10) risks.",
        "footer": "",
        "settings": [
            {
                "key": "enablepurge",
                "display_name": "Enable Hard Purge",
                "type": "bool",
                "help_text": "When ON, expired messages are hard-deleted from the database (transactional purge). When OFF, the sweeper falls back to Mattermost's soft-delete.",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "purgeschemaallowlist",
                "display_name": "Purge Schema Allowlist",
                "type": "text",
                "help_text": "Comma-separated Mattermost server version prefixes whose DB schema has been verified for hard purge (e.g. 10.,11.). The hard purge is skipped (fail-safe) on any other version. Edit after upgrading Mattermost.",
                "placeholder": "",
                "default": "10.,11.",
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`);

export default manifest;
